//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_school
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company_tbl()
        {
            this.internship_request_tbl = new HashSet<internship_request_tbl>();
            this.introducing_tbl = new HashSet<introducing_tbl>();
        }
    
        public int company_code { get; set; }
        public string company_activity { get; set; }
        public string company_type { get; set; }
        public string company_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<internship_request_tbl> internship_request_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<introducing_tbl> introducing_tbl { get; set; }
    }
}
