//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_school
{
    using System;
    using System.Collections.Generic;
    
    public partial class degree_tbl
    {
        public int degree_code { get; set; }
        public string degree_name { get; set; }
        public string degree_organ { get; set; }
        public string degree_credential { get; set; }
        public string degree_score { get; set; }
    }
}
