//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_school
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_tbl
    {
        public int history_id { get; set; }
        public int intern_national_code { get; set; }
        public string history_titile { get; set; }
        public string history_period { get; set; }
        public string history_wages { get; set; }
        public string history_manager { get; set; }
    
        public virtual intern_tbl intern_tbl { get; set; }
    }
}
