//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_school
{
    using System;
    using System.Collections.Generic;
    
    public partial class internship_request_tbl
    {
        public int request_num { get; set; }
        public string request_date { get; set; }
        public Nullable<int> company_code { get; set; }
        public string request_conditiions { get; set; }
    
        public virtual company_tbl company_tbl { get; set; }
    }
}
