//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_school
{
    using System;
    using System.Collections.Generic;
    
    public partial class intern_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public intern_tbl()
        {
            this.register_tbl = new HashSet<register_tbl>();
        }
    
        public string intern_national_code { get; set; }
        public string intern_name { get; set; }
        public Nullable<System.DateTime> intern_birthday { get; set; }
        public string intern_job { get; set; }
        public string intern_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<register_tbl> register_tbl { get; set; }
    }
}
