//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_school
{
    using System;
    using System.Collections.Generic;
    
    public partial class introducing_tbl
    {
        public int introducing_id { get; set; }
        public Nullable<int> manager_personal_code { get; set; }
        public Nullable<int> intern_national_code { get; set; }
        public Nullable<int> company_code { get; set; }
        public string introducing_conditions { get; set; }
    
        public virtual company_tbl company_tbl { get; set; }
        public virtual intern_tbl intern_tbl { get; set; }
        public virtual manager_tbl manager_tbl { get; set; }
    }
}
