//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_school
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_tbl
    {
        public int intern_national_code { get; set; }
        public string register_id { get; set; }
        public string payment_date { get; set; }
        public string payment_tracking_code { get; set; }
        public string payment_amount { get; set; }
        public string bank_code { get; set; }
    }
}
