//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Technical_school
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bank_tbl> bank_tbl { get; set; }
        public virtual DbSet<bayati> bayatis { get; set; }
        public virtual DbSet<company_tbl> company_tbl { get; set; }
        public virtual DbSet<course_tbl> course_tbl { get; set; }
        public virtual DbSet<degree_tbl> degree_tbl { get; set; }
        public virtual DbSet<employee_tbl> employee_tbl { get; set; }
        public virtual DbSet<gruduation_tbl> gruduation_tbl { get; set; }
        public virtual DbSet<history_tbl> history_tbl { get; set; }
        public virtual DbSet<intern_tbl> intern_tbl { get; set; }
        public virtual DbSet<internship_request_tbl> internship_request_tbl { get; set; }
        public virtual DbSet<introducing_tbl> introducing_tbl { get; set; }
        public virtual DbSet<manager_tbl> manager_tbl { get; set; }
        public virtual DbSet<master_tbl> master_tbl { get; set; }
        public virtual DbSet<register_tbl> register_tbl { get; set; }
        public virtual DbSet<source_tbl> source_tbl { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<payment_tbl> payment_tbl { get; set; }
    }
}
